name: CI Test

on: pull_request

ci-test-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test with docker-compose stack
        run: |
          make setup
          make test-ci